### ISSUE TITLE
Master todo thread

### ISSUE THREAD

**Issue by simison** [agenda/agenda-rest#4]
I just want to list here quickly what could/should be done. Each topic could be its own issue/PR.

### Janitorial
We'd love to have this repo in line with our other repos (see @Agenda) and that mostly includes 
- [x] using [`xo`](https://www.npmjs.com/package/xo),
- [x] codebase in ES6,
- [x] tests with [`ava`](http://npmjs.com/package/ava). 
- [x] Add this to our Travis CI

I already wrote at Slack:
>just a reminder that since that project has been independent, they might be opinionated about coding style, libraries to use etc.
>
> Nicer to have everything in line (`xo` etc) under the org, but should not become a blocker if they strongly prefer not to.

;-) Would love to hear your thoughts on that @keyvan-m-sadeghi 

### Bigger picture tasks / questions

- [x] map out what requirements Agendash has from the API and if this library matches them.
- [x] map out if this library works with the latest Agenda (1.x).
- [x] map out Agenda methods
- [ ] Write Agendash to use this package instead its built-in API
- [ ] if we need to make breaking changes here, can we or do we need to maintain backwards compatibility (might not be much work)?
- [x] Should we add versioning to the API (`/v1/` in routes etc)?

_What do you think?_

**Comment by OmgImAlexis** [comment]
I'll take clean up. I've already got `xo --fix` running as we speak. Let's hope @keyvan-m-sadeghi is cool with that.

**Comment by 2bigO** [comment]
I'm always cool with progress, do anything you see fit

**Comment by 2bigO** [comment]
Renaming this project to `agenda-api` is a very neat idea.
Also, what's you opinion on renaming `/api/new` to `/api/define`?
It's more consistent with Agenda terminology, also semantically makes sense, since one can re-define an already existing job and change the URL with this endpoint.

**Comment by OmgImAlexis** [comment]
If we're going to do REST properly we shouldn't really have a `/new` we should `POST` to `/job` for a new one, `DELETE` to remove, `PUT` for update, etc.

**Comment by simison** [comment]
☝️ I second @OmgImAlexis  

If the API isn't going to be [restful](https://developer.mozilla.org/en-US/docs/Glossary/REST), we should indeed rename it. 

That said, making it restful would make it easier to reason about. REST kinda dictates routes and everything to us so we wouldn't need to spend time designing the API that much but building cool stuff with it instead. :-)

Thanks for bringing this up @keyvan-m-sadeghi !

**Comment by 2bigO** [comment]
Alright, that makes perfect sense. Will rename to `/api/job` and also add `PUT` and `DELETE` tonight or tomo 👍

**Comment by 2bigO** [comment]
> If we're going to do REST properly we shouldn't really have a /new we should POST to /job for a new one, DELETE to remove, PUT for update, etc.

Done. Only `DELETE` remains

**Comment by simison** [comment]
ref: https://github.com/agenda/agenda-rest/pull/10

**Comment by OmgImAlexis** [comment]
@keyvan-m-sadeghi it'd be a smart idea to allow `/api/job/:jobId` to be a specific job if you haven't already added that.

**Comment by 2bigO** [comment]
@OmgImAlexis you mean a `GET` for a specific job? Yeah, sounds good

**Comment by OmgImAlexis** [comment]
As well as updating a single one. `/api/job` should really affect all jobs since that's how REST works.

**Comment by 2bigO** [comment]
Hmmm this last suggestion doesn't resonate with me. The way I see it, _"to `POST` to `job`"_ reads as _introducing a single job_. If it was `jobs` I'd get it. Also I'm not sure who'd need a batch update on all jobs' URLs.

**Comment by 2bigO** [comment]
Another point, Agenda abstracts away implementation details such as Mongo IDs (e.g. `jobId`), the `name` for each job is the unique getter. So I guess `/api/job/:name` is more suitable. And we actually already have that since this would need to be a `POST` or `PUT` accompanied with a `body`, hence `:name` could be moved to the `body` and that we already have. What do you think?

**Comment by 2bigO** [comment]
Huh the last part of what I just said is wrong, it is a `GET` request, so `/api/job/:name` makes perfect sense. Let me know your opinion and I'll add the endpoint accordingly

**Comment by OmgImAlexis** [comment]
@keyvan-m-sadeghi This would be RESTFUL.

```
GET /api/job -> Return all jobs
POST /api/job -> Create a new job
PUT /api/job -> Update all jobs
DELETE /api/job -> Delete all jobs

GET /api/job/:jobName -> Return all jobs with this name
POST /api/job/:jobName -> Create a new job with this name
PUT /api/job/:jobName -> Update all jobs with this name
DELETE /api/job/:jobName -> Delete all jobs with this name

GET /api/job/:jobName/:jobId -> Return single jobs with this name and id
POST /api/job/:jobName/:jobId -> Create a new job with this name and id
PUT /api/job/:jobName/:jobId -> Update a single job with this name and id
DELETE /api/job/:jobName/:jobId -> Delete a single job with this name and id
```

**Comment by simison** [comment]
Yep ☝️  Tho it would be even more RESTFUL if URL path would be `/api/jobs/*` ;-D

Nice list, thanks @OmgImAlexis 

I'll just throw in what Agendash seems to [use](https://github.com/agenda/agendash/blob/b7b8ac301cb41e146aaf52a1806af4029cb7d405/lib/middlewares/express.js) currently:
- `GET /api`
- `POST /api/jobs/requeue` (takes multiple ids)
- `POST /api/jobs/delete` (takes multiple ids)
- `POST /api/jobs/create`

Agendash UI does these features currently:
- Delete many jobs
- Requeue many jobs
- Requeue one job
- Delete one job
- Schedule a job
- Read all the jobs (filtered by name)

Needs to be able to categorise jobs as:
- Scheduled
- Queued
- Running
- Completed
- Failed
- Repeating

**Comment by simison** [comment]
I'll also list what Agenda does, more or less —

[Define a job](https://github.com/agenda/agenda#definejobname-options-fn)

[Creating jobs](https://github.com/agenda/agenda#creating-jobs):
- every
- schedule
- now
- create (+save)

[Manually working with a job](https://github.com/agenda/agenda#manually-working-with-a-job):
- repeatEvery
- repeatAt
- schedule
- priority
- unique
- fail
- run
- save
- remove
- touch
- disable
- enable

[Managing multiple jobs](https://github.com/agenda/agenda#managing-jobs):
- jobs (_query jobs_)
- purge (_removes all jobs in the database without defined behaviors_)
- cancel

Now, out of all these lists we should be able to see how our API should look like. Should cover at least Agendash's needs. Suggestions? :-)

**Comment by OmgImAlexis** [comment]
I'm good with adding versioning in the API as we can handle old traffic going to the API without a version number and then return a deprecated notice.

We may need to push a minor update to the old version that just checks if the endpoint returns a certain HTTP code(maybe 410?) and then errors out asking them to update.

**Comment by 2bigO** [comment]
> @keyvan-m-sadeghi This would be RESTFUL.

OK now I understand.

I added these three:
```
GET /api/job -> Return all jobs
POST /api/job -> Create a new job
PUT /api/job/:jobName -> Update all jobs with this name
```

And I'm done for this weekend ;)

**Comment by 2bigO** [comment]
+1 for versioning

**Comment by simison** [comment]
Some good food for thought about multiple IDs: https://stackoverflow.com/a/9372278/1984644

i.e. `DELETE /job?id=1,2,3` not `DELETE /job/1,2,3`

**Comment by simison** [comment]
I'll close this old project issue — any remaining todos can be worked out in individual issues. :-)
